version: "2"
linters:
  default: all
  disable:
    - depguard
    - gochecknoglobals
    - godot
    - ireturn
    - nolintlint
    - nonamedreturns
    - wrapcheck
    - wsl
  settings:
    lll:
      line-length: 150
    varnamelen:
      ignore-names:
        - tt
  exclusions:
    generated: lax
    rules:
      - linters:
          - containedctx
          - funlen
        path: _test\.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
