linters:
  enable-all: true
  disable:
    - deadcode # deprecated
    - depguard
    - exhaustivestruct # deprecated
    - gochecknoglobals
    - godot
    - golint # deprecated
    - ifshort # deprecated
    - interfacer # deprecated
    - ireturn
    - maligned # deprecated
    - nolintlint
    - nonamedreturns
    - nosnakecase # deprecated
    - scopelint # deprecated
    - structcheck # deprecated
    - varcheck # deprecated
    - wrapcheck

linters-settings:
  lll:
    line-length: 150
  varnamelen:
    ignore-names:
      - tt

issues:
  exclude-use-default: false
