name: Dependabot Auto Merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: |
          gh pr review --approve ${{github.event.pull_request.html_url}}
          gh pr merge --auto --merge ${{github.event.pull_request.html_url}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
